apiVersion: v1
kind: Secret
type: Opaque
data:
  FREEDNS_USERNAME: {{ required "Please provide the value of freedns.auth.FREEDNS_USERNAME" .Values.freedns.auth.FREEDNS_USERNAME | b64enc | quote }}
  FREEDNS_PASSWORD: {{ required "Please provide the value of freedns.auth.FREEDNS_PASSWORD" .Values.freedns.auth.FREEDNS_PASSWORD | b64enc | quote }}
metadata:
  name: {{ include "freedns-webhook.fullname" . }}-auth
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "freedns-webhook.name" . }}
    chart: {{ include "freedns-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
